services:
  - type: web
    name: agarfi-client
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_SOCKET_URL
        sync: false

